init:
    define notif = Character()
    define bella = Character("Bella", color="#eb974e")
    define me = DynamicCharacter("FIRST_NAME", color="#333333")
    define narrator = Character(what_italic=True)
    define announcement = Character("Announcement", color="#3a539b")
    define kid = Character("Kid", color="#5c97bf")
    define akz = Character("???", color="#5c97bf")
    define kz = Character("Kazimir", color="#5c97bf")
    define mir = Character("Miriam", color="#19b5fe")
    define boris = Character("Boris", color="#f9b42d")
    define layla = Character("Layla", color="#1e824c")
    define kurtboy_anon = Character("???", color="#d91e18")
    define kurtboy = Character("Kurt", color="#d91e18")
    define kurt = Character("Kurt", color="#d91e18")
    define ahans = Character("???", color="#1e824c")
    define hans = Character("Thirty-one", color="#1e824c")
    define vio = Character("Violet", color="#963694")

    define duck = Character("Duck", color="#e47833")
