init:
    define notif = Character()
    define notif_b = Character(what_color="#f0f0f0", window_style="say_black_window")
    define bella = Character(_("Bella"), color="#ffa123")
    define me = DynamicCharacter("FIRST_NAME", color="#061c6f")
    #define me_b = DynamicCharacter("FIRST_NAME", color="#061c6f", what_color="#f0f0f0", window_style="say_black_window")
    define narrator = Character(what_italic=True)
    define narr_b = Character(what_italic=True, what_color="#f0f0f0", window_style="say_black_window")
    define announcement = Character(_("Announcement"), color="#2295a5")
    define announcement_b = Character(_("Announcement"), color="#2295a5", what_color="#f0f0f0", window_style="say_black_window")
    define kid = Character(_("Kid"), color="#d7449d")
    define akz = Character(_("???"), color="#d7449d")
    define kz = Character(_("Kazimir"), color="#d7449d")
    define mir = Character(_("Miriam"), color="#fe628a")
    define boris = Character(_("Boris"), color="#2f7103")
    define layla = Character(_("Layla"), color="#597bd5")
    define kurtboy_anon = Character(_("???"), color="#d91e18")
    define kurtboy = Character(_("Kurt"), color="#d91e18")
    define kurt = Character(_("Kurt"), color="#d91e18")
    define ahans = Character(_("???"), color="#51706b")
    define hans = Character(_("Thirty-one"), color="#51706b")
    define hans_b = Character(_("Thirty-one"), color="#51706b", what_color="#f0f0f0", window_style="say_black_window")
    define vio = Character(_("Violet"), color="#956fbc")

    define duck = Character(_("Duck"), color="#e47833", what_color="#f0f0f0", window_style="say_black_window")
