# TODO: Translation updated at 2020-08-18 00:17

translate russian strings:

    # game/options.rpy:15
    old "Limbus inc"
    new "Limbus inc"

    # game/options.rpy:32
    old "This game was created in two weeks of July and August 2020 specially for{p}“I Can't Write But Want To Tell A Story” game jam ({a=https://itch.io/jam/i-cant-write-but-want-to-tell-a-story}link{/a}).\n\n© 2020 IT Happens\n\n© 2020 {a=https://andtaksoidet.games/en/}And Tak Soidet Games{/a}\n\nP.S. This game {u}does have{/u} a duck content."
    new "Эта игра была создана за две недели июля и августа 2020 специально для джема “I Can't Write But Want To Tell A Story” ({a=https://itch.io/jam/i-cant-write-but-want-to-tell-a-story}ссылка{/a}).\n\n© 2020 IT Happens\n\n© 2020 {a=https://andtaksoidet.games/}And Tak Soidet Games{/a}\n\nP.S. В этой игре {u}есть{/u} утка."

# TODO: Translation updated at 2020-08-20 01:56

translate russian strings:

    # game/options.rpy:41
    old "{size=20}This game uses Exo 2 font by Natanael Gama from {a=https://fonts.google.com/specimen/Exo+2}Google Fonts{/a} ({a=https://scripts.sil.org/OFL}license{/a}). This game uses “technological sense png” designed by {image=qian_tu_wang.png} from {a=https://pngtree.com/}pngtree.com{/a} ({a=https://pngtree.com/legal/license-terms}license{/a}). This game uses icons made by {a=https://www.flaticon.com/authors/freepik}Freepik{/a} from {a=https://www.flaticon.com/}www.flaticon.com{/a} ({a=https://www.freepikcompany.com/legal#nav-flaticon-agreement}license{/a}). This game uses image by {a=https://www.pexels.com/@pixabay}Pixabay{/a} from {a=https://www.pexels.com/}Pexels.com{/a} ({a=https://www.pexels.com/creative-commons-images/}license{/a}). This game contains the image by {a=https://pixabay.com/ru/users/monstreh-637659/}Anna Kulikova{/a} from Pixbay ({a=https://pixabay.com/ru/service/license/}license{/a}). This game uses sounds from {a=https://freesound.org}FreeSound.org{/a} by {a=https://freesound.org/people/nsstudios/}nsstudios{/a}, {a=https://freesound.org/people/LoafDV/}LoafDV{/a}, {a=https://freesound.org/people/Aysonny/}Aysonny{/a}, {a=https://freesound.org/people/MelvinJaepel/}MelvinJaepel{/a}, {a=https://freesound.org/people/BenjaminNelan/}BenjaminNelan{/a}, {a=https://freesound.org/people/Anthousai/}Anthousai{/a}, {a=https://freesound.org/people/lsestep/}lsestep{/a}, {a=https://freesound.org/people/michorvath/}michorvath{/a}, {a=https://freesound.org/people/copyc4t/}copyc4t{/a}, {a=https://freesound.org/people/loudernoises/}loudernoises{/a}, {a=https://freesound.org/people/dkiller2204/}dkiller2204{/a}, {a=https://freesound.org/people/paulmessier/}paulmessier{/a}, {a=https://freesound.org/people/WhaTThes/}WhaTThes{/a}, {a=https://freesound.org/people/Sheyvan/}Sheyvan{/a}, {a=https://freesound.org/people/DrMaysta/}DrMaysta{/a}, {a=https://freesound.org/people/taurindb/}taurindb{/a}, {a=https://freesound.org/people/squashy555/}squashy555{/a}, {a=https://freesound.org/people/Robinhood76/}Robinhood76{/a}, {a=https://freesound.org/people/the_very_Real_Horst/}the_very_Real_Horst{/a}, and others (licensed under {a=http://creativecommons.org/publicdomain/zero/1.0/}CC0{/a} or {a=http://creativecommons.org/licenses/by/3.0/}CC-BY-3.0{/a}). {/size}"
    new "{size=20}В этой игре использован шрифт Exo 2, автор Натаниэль Гама, из коллекции {a=https://fonts.google.com/specimen/Exo+2}Google Fonts{/a} ({a=https://scripts.sil.org/OFL}лицензия{/a}). В этой игре использован “technological sense png”, автор {image=qian_tu_wang.png}, с сайта {a=https://pngtree.com/}pngtree.com{/a} ({a=https://pngtree.com/legal/license-terms}лицензия{/a}). В этой игре использованы значки автора {a=https://www.flaticon.com/authors/freepik}Freepik{/a} с сайта {a=https://www.flaticon.com/}www.flaticon.com{/a} ({a=https://www.freepikcompany.com/legal#nav-flaticon-agreement}лицензия{/a}). В этой игре использовано изображение за авторством {a=https://www.pexels.com/@pixabay}Pixabay{/a} с сайта {a=https://www.pexels.com/}Pexels.com{/a} ({a=https://www.pexels.com/creative-commons-images/}лицензия{/a}). В этой игре есть изображение за авторством {a=https://pixabay.com/ru/users/monstreh-637659/}Анны Куликовой{/a} с сайта Pixbay ({a=https://pixabay.com/ru/service/license/}license{/a}). В этой игре использованы звуки с сайта {a=https://freesound.org}FreeSound.org{/a} за авторством {a=https://freesound.org/people/nsstudios/}nsstudios{/a}, {a=https://freesound.org/people/LoafDV/}LoafDV{/a}, {a=https://freesound.org/people/Aysonny/}Aysonny{/a}, {a=https://freesound.org/people/MelvinJaepel/}MelvinJaepel{/a}, {a=https://freesound.org/people/BenjaminNelan/}BenjaminNelan{/a}, {a=https://freesound.org/people/Anthousai/}Anthousai{/a}, {a=https://freesound.org/people/lsestep/}lsestep{/a}, {a=https://freesound.org/people/michorvath/}michorvath{/a}, {a=https://freesound.org/people/copyc4t/}copyc4t{/a}, {a=https://freesound.org/people/loudernoises/}loudernoises{/a}, {a=https://freesound.org/people/dkiller2204/}dkiller2204{/a}, {a=https://freesound.org/people/paulmessier/}paulmessier{/a}, {a=https://freesound.org/people/WhaTThes/}WhaTThes{/a}, {a=https://freesound.org/people/Sheyvan/}Sheyvan{/a}, {a=https://freesound.org/people/DrMaysta/}DrMaysta{/a}, {a=https://freesound.org/people/taurindb/}taurindb{/a}, {a=https://freesound.org/people/squashy555/}squashy555{/a}, {a=https://freesound.org/people/Robinhood76/}Robinhood76{/a}, {a=https://freesound.org/people/the_very_Real_Horst/}the_very_Real_Horst{/a} и других (по лицензиям {a=http://creativecommons.org/publicdomain/zero/1.0/}CC0{/a} либо {a=http://creativecommons.org/licenses/by/3.0/}CC-BY-3.0{/a}).{/size}"

